### ISSUE TITLE
How to run on PC / Desktop

### ISSUE THREAD

**Issue by SrinivasuluCharupally** [flowdriveai/flowpilot#38]
Hi,
I am trying to setup it on PC / Desktop, Intel CPU + Ubuntu 20.04.
I followed the install steps from here : https://github.com/flowdriveai/flowpilot/wiki/Installation#installing-on-desktop
Then I followed "Running on Simulator" steps from here : https://github.com/flowdriveai/flowpilot/wiki/Running-On-Simulation#following-steps-will-help-you-get-carla-simulation---flowpilot-integration-up-and-running

I got confused with these following two steps... Could you help to clarigy

- start carla simulation using ./CarlaUE4.sh -RenderOffScreen
- In one terminal, launch flowpilot and in other, launch python tool/sim/bridge.py

**This means, total 3 terminals do i need to launch, one for "./CarlaUE4.sh -RenderOffScreen", one for "./launch_flowpilot.sh" and one for "python tool/sim/bridge.py"**

Is that correct ?
and, Do i need to have Camera or SmartPhone to run the application ?

**Comment by MankaranSingh** [comment]
Yes, you need to run them parallely in 3 seperate terminals.

**Comment by SrinivasuluCharupally** [comment]
Thanks Mankaran. One more thing.. This is what i am getting when try to run .
I am running from SSH. 

`(flowpilot) che7@che7-w30871:~/flowpilot$ ./CarlaUE4.sh -RenderOffScreen
4.26.2-0+++UE4+Release-4.26 522 0
Disabling core dumps.
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.


che7@che7-w30871:~/flowpilot$ ./launch_flowpilot.sh
logmessaged thermald_ statsd keyvald flowpilot pandad deleter flowinitd
logmessaged thermald_ statsd keyvald flowpilot pandad deleter flowinitd
logmessaged thermald_ statsd keyvald flowpilot pandad deleter flowinitd
logmessaged thermald_ statsd keyvald flowpilot pandad deleter flowinitd
accepted_terms False
completed_training False
ignition False


che7@che7-w30871:~/flowpilot$ python3 tools/sim/bridge.py
Restarting bridge. Error: time-out of 5000ms while waiting for the simulator, make sure the simulator is ready and connected to 127.0.0.1:2000
Restarting bridge. Error: time-out of 5000ms while waiting for the simulator, make sure the simulator is ready and connected to 127.0.0.1:2000
Restarting bridge. Error: time-out of 5000ms while waiting for the simulator, make sure the simulator is ready and connected to 127.0.0.1:2000

`

**Comment by RaghavPrabhakar66** [comment]
```bash
(flowpilot) che7@che7-w30871:~/flowpilot$ ./CarlaUE4.sh -RenderOffScreen
4.26.2-0+++UE4+Release-4.26 522 0
Disabling core dumps.
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
```

Is Carla running properly?

**Comment by SrinivasuluCharupally** [comment]
Not sure, doing it for the first time.
i running it from SSH.

**Comment by MankaranSingh** [comment]
You will have to make sure carla is running. If you remove the `RenderOffScreen` arg, it should show the carla window which will confirm its up and running

**Comment by SrinivasuluCharupally** [comment]
Could you please confirm this error.  this is OK or, Not ?

(flowpilot) che7@che7-w30871:~/flowpilot$ **python scripts/dummy_params.py**
<frozen importlib._bootstrap>:228: RuntimeWarning: compiletime version 3.8 of module 'common.params_pyx' does not match runtime version 3.9
<frozen importlib._bootstrap>:228: RuntimeWarning: compiletime version 3.8 of module 'common.transformations.transformations' does not match runtime version 3.9
done

**Comment by MankaranSingh** [comment]
I think you compiled (ran `scons` command) without entering the flowpilot env (`pip env shell`) 
Do `pip env shell` then `scons` in flowpilot root directory then this warning should go away

**Comment by SrinivasuluCharupally** [comment]
Got it, thanks Mankaran.

**Comment by SrinivasuluCharupally** [comment]
MankaranSingh - We tried the steps but that did not work for us. Attaching a screenRecording of what we did. Could tell us what was the issue ?

jFYI ... Prithiveen from our team tried the steps.

https://github.com/flowdriveai/flowpilot/assets/7656634/83bd1ae9-1baf-4457-a442-d073f2c09113


https://github.com/PrithiveenKumaarRamkumar

**Comment by RaghavPrabhakar66** [comment]
@SrinivasuluCharupally Can you share the output of following command.
```bash
file tmp.avi
```

**Comment by SrinivasuluCharupally** [comment]
@RaghavPrabhakar66  
che7@che7-w30871:~/flowpilot/selfdrive/assets$ file tmp
**tmp: RIFF (little-endian) data, AVI, 1164 x 874, 25.00 fps, video: Motion JPEG**

**Comment by PrithiveenKumaarRamkumar** [comment]
@MankaranSingh @RaghavPrabhakar66 
Able to successfully launch flowpilot app now :)
bridge.py still renders a Segmentation fault (core dumped) error 

https://github.com/flowdriveai/flowpilot/assets/99075098/f5949cfb-b580-4fb4-badc-8821c5c299f1

**Comment by MankaranSingh** [comment]
I'd recommed you clean the build using `scons -c`.
I am not sure but maybe when you interchanged the python version (3.10) and ran scons that built some files that were not compatible.

**Comment by SrinivasuluCharupally** [comment]
@MankaranSingh , @RaghavPrabhakar66  - Could we have short call some time next week to look into the issues ?
We are from Valeo team / org , trying to explore the option for different platform.

**Comment by PrithiveenKumaarRamkumar** [comment]
@MankaranSingh @RaghavPrabhakar66 
Tired cleaning the build using `scons -c` and then building again using `scons` but bridge.py still renders a Segmentation fault (core dumped) error
user journey: [https://drive.google.com/file/d/1h7DjBOh8l7pfuaAKOrPIbo6Kdaa1f4Sl/view?usp=sharing](url)

**Comment by MankaranSingh** [comment]
@PrithiveenKumaarRamkumar @SrinivasuluCharupally 
I am not able to reproduce the issue. It would be helpful if you exactly mention what lines are causing segmenation fault in the script.

**Comment by MankaranSingh** [comment]
@SrinivasuluCharupally the issue is related to the carla-py package provided in this repo. you can try uninstalling that and do `pip install carla==0.9.12` and rerun this.

**Comment by SrinivasuluCharupally** [comment]
@MankaranSingh  - the segfault occurs when try to import the carla  from bridge.py script

Steps:
======
```
#pipenv shell
# scons
# python tools/sim/bridge.py
Segmentation fault
```
===>  this seg fault occur from the  line `import carla`  in the `tools/sim/bridge.py`

**Comment by SrinivasuluCharupally** [comment]
BTW - We tried the above steps with `pip install carla==0.9.12`, `pip3 install carla==0.9.12` and `pip install -e carla-py`.
Result is same all the time, seg fault while importing carla into the `bridge.py`.
I am sure some thing is missing in the README.

**Comment by HiHeXi** [comment]
I also encountered the same problem. Have you solved the problem? If it is resolved, I would like to ask for advice on a solution

> @MankaranSingh @RaghavPrabhakar66 Able to successfully launch flowpilot app now :) bridge.py still renders a Segmentation fault (core dumped) error
> flowpilot_app_journey.mp4

I also encountered the same problem. Have you solved the problem? If it is resolved, I would like to ask for advice on a solution

**Comment by MankaranSingh** [comment]
You can try installing carla like this https://github.com/carla-simulator/carla/issues/1466#issuecomment-522797557

**Comment by SrinivasuluCharupally** [comment]
@MankaranSingh  - could you confirm these steps are correct  for each terminal.  We are running every thing from the `pipenv shell`, check the below steps

**Terminal#1**
----------------------------------
`pipenv shell`
`scons`
`./CarlaUE4.sh -RenderOffScreen`

**Terminal#2**
---------------------------------
`pipenv shell`
`launch_flowpilot.sh`

**Terminal#3**
--------------------------
`pipenv shell`
`python tool/sim/bridge.py`

**Comment by MankaranSingh** [comment]
Your steps are correct. you just need a working carla-python api. Please check this out https://github.com/carla-simulator/carla/issues/1466#issuecomment-522797557

**Comment by HiHeXi** [comment]
> 你的步骤是正确的。 你只需要一个工作carla-蟒蛇。 请看看这个 [卡拉-模拟器/卡拉#1466(注释) ](https://github.com/carla-simulator/carla/issues/1466#issuecomment-522797557)

This method won't work

**Comment by PrithiveenKumaarRamkumar** [comment]
In https://github.com/carla-simulator/carla/issues/1466#issuecomment-522797557 it is recommended to install carla by extracting the .egg files, but the .egg files are for python3.7. 

However, activating the flowpilot environment `pipenv shell` takes you to python3.9 environment

The Carla build documentation https://carla.readthedocs.io/en/latest/build_linux/ and discussions https://github.com/carla-simulator/carla/discussions/4519 says that the PythonAPI is supported till python3.8. I am now able to import carla successfully in python3.7 and python3.8 

Using python3.8 I was able to generate the build using `scons` and run the other scripts successfully but bridge.py renders the following traceback:
```
Traceback (most recent call last):
  File "tools/sim/bridge.py", line 28, in <module>
    pm = messaging.PubMaster(['roadCameraState', 'roadCameraBuffer', 'wideRoadCameraState',
  File "/home/che7/flowpilot/cereal/messaging/__init__.py", line 257, in __init__
    self.sock[s] = pub_sock(s)
  File "/home/che7/flowpilot/cereal/messaging/__init__.py", line 47, in pub_sock
    sock.connect(context, endpoint)
  File "cereal/messaging/messaging_pyx.pyx", line 139, in cereal.messaging.messaging_pyx.PubSocket.connect
    raise MultiplePublishersError
cereal.messaging.messaging_pyx.MultiplePublishersError
```

**Comment by MankaranSingh** [comment]
@PrithiveenKumaarRamkumar for MultiplePublishersError, you'd need to comment out the `ROAD_CAMERA_SOURCE` and wide camera source. This will not start the video publishers and allow publihers from carla bridge script to take over

**Comment by PrithiveenKumaarRamkumar** [comment]
@MankaranSingh Now I am able to run Carla, launch the flowpilot app and run bridge.py from the python3.8 environment but I am not able to "take control of the wheel" in the flowpilot app. Are we missing something here?
https://drive.google.com/file/d/1gLtdT1o6qeKijSyk_YwiPW62gROMnFJn/view?usp=sharing

**Comment by SrinivasuluCharupally** [comment]
@MankaranSingh - We are able to control the Carla output with 1, 2 and W-A-D keys.
Could you tell us how to render with our own video with the environment, we have a local traffic video, would like to see the flowdriver output for that.
Let us know the details.

**Comment by SrinivasuluCharupally** [comment]
@MankaranSingh  - could you guide us on this ?

**Comment by MankaranSingh** [comment]
The video can be specified in `ROAD_CAMERA_SOURCE` in launch script. By default, flowpilot desktop version run on a video only.

**Comment by SrinivasuluCharupally** [comment]
@MankaranSingh  - do we have to launch all the three terminals with the "ROAD_CAMERA_SOURCE" enabled ?
The reason is, we noticed following error with ROAD_CAMERA_SOURCE enabled , you suggested to disable it /comment out. 

Traceback (most recent call last):
  File "tools/sim/bridge.py", line 28, in <module>
    pm = messaging.PubMaster(['roadCameraState', 'roadCameraBuffer', 'wideRoadCameraState',

**Comment by MankaranSingh** [comment]
ROAD_CAMERA_SOURCE needs to be disabled to accept stream from carla
simulation. do not run carla or or bridge.py if you want to run on video

**Comment by SrinivasuluCharupally** [comment]
Hi @MankaranSingh - Sorry for the late repose, we were busy with other projects.
Still  we are not able to render the video.

script:
==================
Attaching our "launch_flowpilot.sh" script.

steps:
=============
pipenv shell
scons
./launch_flowpilot.sh

output
============
attaching screen shot

![Screenshot from 2023-10-30 11-39-41](https://github.com/flowdriveai/flowpilot/assets/7656634/af80c960-e09d-4cd3-8fe9-7f25fb61b184)

[launch_flowpilot.py.txt](https://github.com/flowdriveai/flowpilot/files/13201450/launch_flowpilot.py.txt)

**Comment by PrithiveenKumaarRamkumar** [comment]
Hi @MankaranSingh 
Do we have to make changes on these scripts for using user's input video?
https://github.com/flowdriveai/flowpilot/blob/master/selfdrive/loggerd/video_process.py
https://github.com/flowdriveai/flowpilot/blob/master/selfdrive/loggerd/config.py

**Comment by MankaranSingh** [comment]
The default launchfile when you download it freshly is taking in video input only. you do not need to run bridge.py. 
after launch just run `scripts/dummy_publishers.py` in seperate terminal

**Comment by SrinivasuluCharupally** [comment]
Thanks @MankaranSingh 
I am able to run it now. Attaching screen shots
**one more question** : Would it display the bounding boxes on detected objects ?


![Screenshot from 2023-11-01 17-49-14](https://github.com/flowdriveai/flowpilot/assets/7656634/8f6572db-5492-4959-a16a-fc5ed3101950)
![Screenshot from 2023-11-01 17-50-10](https://github.com/flowdriveai/flowpilot/assets/7656634/072cbf8d-fa41-44ed-9872-29bc92ca6c64)
![Screenshot from 2023-11-01 17-50-15](https://github.com/flowdriveai/flowpilot/assets/7656634/e71adbd9-52b7-4c08-ba42-384f82ff6de1)
![Screenshot from 2023-11-01 17-50-53](https://github.com/flowdriveai/flowpilot/assets/7656634/f86f513e-42d7-4337-84f8-c817f23cdc07)
?

**Comment by MankaranSingh** [comment]
This is an end to end driving model. this dosent outputs

**Comment by SrinivasuluCharupally** [comment]
@MankaranSingh  - I have downloaded a video from web, mp4 format, and  tried to render the video under flowDrive, but seeing following error. You have any idea ?


![Screenshot from 2023-11-02 09-19-08](https://github.com/flowdriveai/flowpilot/assets/7656634/5471290b-514b-4d6a-8805-a24db6d505cd)

**Video download link** : https://www.pexels.com/video/cars-traveling-on-expressway-5382495/

**Comment by MankaranSingh** [comment]
convert video to avi format.

**Comment by SrinivasuluCharupally** [comment]
@MankaranSingh - I tried but did not work.
Does it really requires Calibration & CAN signals ?
it shows "CalibrationError" & "canError".

**Comment by piyushmz** [comment]
Hey @MankaranSingh 
I followed the steps in here https://github.com/flowdriveai/flowpilot/wiki/Running-On-Simulation for running on desktop. I get flowpilot in infinite loop.
ubuntu 20.04
nvidia-driver-535(proprietary tested)
carla= 0.9.12
I've given `ROAD_CAMERA_SOURCE="test.avi"` and Iaunched flowpilot following is the o/p I get on after running. 

```
[main] INFO org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for linear algebra: 2
[main] INFO org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory - Binary level Generic x86 optimization level AVX/AVX2
[main] INFO org.nd4j.nativeblas.Nd4jBlas - Number of threads used for OpenMP BLAS: 2
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CPU]; OS: [Linux]
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [24]; Memory: [7.8GB];
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [OPENBLAS]
[main] INFO org.nd4j.linalg.cpu.nativecpu.CpuBackend - Backend build information:
 GCC: "7.5.0"
STD version: 201103L
DEFAULT_ENGINE: samediff::ENGINE_CPU
HAVE_FLATBUFFERS
HAVE_OPENBLAS
[ERROR:0] global /home/runner/work/opencv/opencv/opencv-4.5.1/modules/videoio/src/cap.cpp (142) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.1) /home/runner/work/opencv/opencv/opencv-4.5.1/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): /home/rp/Downloads/testhd.avi in function 'icvExtractPattern'


WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by ai.flow.common.BufferUtils (file:/home/rp/flowpilot/common/build/libs/common-0.0.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of ai.flow.common.BufferUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[main] INFO ai.flow.launcher.FlowInitd - Connected to the FlowInit daemon
[ERROR:0] global /home/runner/work/opencv/opencv/opencv-4.5.1/modules/videoio/src/cap.cpp (142) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.1) /home/runner/work/opencv/opencv/opencv-4.5.1/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): /home/rp/flowpilot/selfdrive/assets/videos/intro.avi in function 'icvExtractPattern'


Exception in thread "camerad:roadCameraState" CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.1) /home/runner/work/opencv/opencv/opencv-4.5.1/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
]
        at org.opencv.imgproc.Imgproc.cvtColor_1(Native Method)
        at org.opencv.imgproc.Imgproc.cvtColor(Imgproc.java:6842)
        at ai.flow.sensor.camera.CameraManager.processFrame(CameraManager.java:112)
        at ai.flow.sensor.camera.CameraManager.run(CameraManager.java:165)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
Is there any hardcoded path like `/home/runner/*` somewhere in flowpilot

If I comment out `ROAD_CAMERA_SOURCE` and start carla, flowpilot is always into infinite loop and nothing is detected.

**Comment by piyushmz** [comment]
so I was testing with a downloaded mp4 file which I converted to avi and I placed the path in `ROAD_CAMERA_SOURCE` but it didn't work. The `selfdrive/assets/tmp` does work with flowpilot. As of bridging of carla with flowpilot I get segmentation fault.

**Comment by pengjunxing** [comment]
> 谢谢@MankaranSingh 我现在可以运行它了。附上屏幕截图 **还有一个问题**：它会在检测到的物体上显示边界框吗？
> 
> ![2023-11-01 17-49-14 的截图](https://private-user-images.githubusercontent.com/7656634/279672428-8f6572db-5492-4959-a16a-fc5ed3101950.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5MzU5MTAsIm5iZiI6MTczNjkzNTYxMCwicGF0aCI6Ii83NjU2NjM0LzI3OTY3MjQyOC04ZjY1NzJkYi01NDkyLTQ5NTktYTE2YS1mYzVlZDMxMDE5NTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTVUMTAwNjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzM3Njc4OTQ5NWU1OTFkNzBhMzM4NjYxNzQwYzk5MjBlYjc5MGE5MGMzYTAxYzBlZWZiNWU3MzI1ZTZiOTVjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2kzHjy1XUv2nUHP8_89Iy9hjDKDdyvdQz8RGXfGl2ec) ![2023-11-01 17-50-10 的截图](https://private-user-images.githubusercontent.com/7656634/279672445-072cbf8d-fa41-44ed-9872-29bc92ca6c64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5MzU5MTAsIm5iZiI6MTczNjkzNTYxMCwicGF0aCI6Ii83NjU2NjM0LzI3OTY3MjQ0NS0wNzJjYmY4ZC1mYTQxLTQ0ZWQtOTg3Mi0yOWJjOTJjYTZjNjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTVUMTAwNjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmE2NmVmNzViMTFmMTI3ZTIyYzg0OTUxZWJlNzY0YWZmM2U5ZTM5NTQyOGMzOGIzZmY4NWFmN2Q3ZTMzNWEwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5xaU4tgDWp5d2KZW9pnbr4eM43zhWlIBfEgJdr9xszU) ![2023-11-01 17-50-15 的截图](https://private-user-images.githubusercontent.com/7656634/279672456-e71adbd9-52b7-4c08-ba42-384f82ff6de1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5MzU5MTAsIm5iZiI6MTczNjkzNTYxMCwicGF0aCI6Ii83NjU2NjM0LzI3OTY3MjQ1Ni1lNzFhZGJkOS01MmI3LTRjMDgtYmE0Mi0zODRmODJmZjZkZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTVUMTAwNjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDY4YTBmNmIyMGU0NzViYjY3NDA4YmEzYzU2NjA4ZDJiYzY0MmIxZWMxMzRlMmZiOWViODlkODg4OGZhOWI4NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wLmU5droiy19Cmb6pxM7bEgFQUWts5Us2GqoHsR3FvQ) ![2023-11-01 17-50-53 的截图](https://private-user-images.githubusercontent.com/7656634/279672465-f86f513e-42d7-4337-84f8-c817f23cdc07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5MzU5MTAsIm5iZiI6MTczNjkzNTYxMCwicGF0aCI6Ii83NjU2NjM0LzI3OTY3MjQ2NS1mODZmNTEzZS00MmQ3LTQzMzctODRmOC1jODE3ZjIzY2RjMDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTVUMTAwNjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OThmYTk5OGE5OTYxMzIwZTQ2Yzg2MmU1N2IxOWM2ZmY4ODIzZWRjOWU0ZGQ1ZmZmYTc0ZjdmNTFjNTNlNmFlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.79-jScBMDThlXkfjk6djP2D4eJUpcXvXnKW14ncZ-is) ？

Hello, how can I implement flowpilot on the video source?

**Comment by pengjunxing** [comment]
> 谢谢@MankaranSingh 我现在可以运行它了。附上屏幕截图 **还有一个问题**：它会在检测到的物体上显示边界框吗？
> 
> ![2023-11-01 17-49-14 的截图](https://private-user-images.githubusercontent.com/7656634/279672428-8f6572db-5492-4959-a16a-fc5ed3101950.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5MzY0ODksIm5iZiI6MTczNjkzNjE4OSwicGF0aCI6Ii83NjU2NjM0LzI3OTY3MjQyOC04ZjY1NzJkYi01NDkyLTQ5NTktYTE2YS1mYzVlZDMxMDE5NTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTVUMTAxNjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzU2MDVhMjcyMjUyM2VlNTJjMTEzNDU0Mzc3MmZiMWMwODk1Zjg2MzgxMDRlM2I2ZTliNGZjYTFiZGQwNjQwYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2YBzMwrWzAFnvvvl3hyrlGTsPpTgLqzmhWUUX_vViuk) ![2023-11-01 17-50-10 的截图](https://private-user-images.githubusercontent.com/7656634/279672445-072cbf8d-fa41-44ed-9872-29bc92ca6c64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5MzY0ODksIm5iZiI6MTczNjkzNjE4OSwicGF0aCI6Ii83NjU2NjM0LzI3OTY3MjQ0NS0wNzJjYmY4ZC1mYTQxLTQ0ZWQtOTg3Mi0yOWJjOTJjYTZjNjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTVUMTAxNjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjQ3YmE5ODE3MDhjNWRkYWNiN2RjOTRkOGQ1NTYxOGJiMmRiZmRmMWQ3ZmEwNWJlZDhiODUxNzY1NGE0MmJmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.PED2KU4fP1Xcbo2Mqn6lNUPp7-On5lerVWxd1kOxK_s) ![2023-11-01 17-50-15 的截图](https://private-user-images.githubusercontent.com/7656634/279672456-e71adbd9-52b7-4c08-ba42-384f82ff6de1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5MzY0ODksIm5iZiI6MTczNjkzNjE4OSwicGF0aCI6Ii83NjU2NjM0LzI3OTY3MjQ1Ni1lNzFhZGJkOS01MmI3LTRjMDgtYmE0Mi0zODRmODJmZjZkZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTVUMTAxNjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWE5MjlhYjMxNDJmNDdiODcyNjg1MWFiYTY1ZTE3MWE0NWIzYTY1ZWYzYTg0NjA1ODQ3MDUwOGM4NGVkNTUxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.QjzNbhSB8FZY2JTv7pf7A05sq-GUXdtXpY-RGeIJK_4) ![2023-11-01 17-50-53 的截图](https://private-user-images.githubusercontent.com/7656634/279672465-f86f513e-42d7-4337-84f8-c817f23cdc07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5MzY0ODksIm5iZiI6MTczNjkzNjE4OSwicGF0aCI6Ii83NjU2NjM0LzI3OTY3MjQ2NS1mODZmNTEzZS00MmQ3LTQzMzctODRmOC1jODE3ZjIzY2RjMDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTVUMTAxNjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2M2OWNlYjk2ZjAxNzg5MWQwNDkwMGQyOTdlNDZlY2I3YzUyNTNjZWI2NGM5ZjY4ZjU5ZWQ4NTBhYmM5NzVmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.9nCoNAsnBYUn4bCnwTxah2_XOj8gffr7Nv-mAMuJlxY) ？

can you publish a video for how to get this result？
